language: csharp
mono: none
dotnet: 2.1.502

install:
  - cd AlipaySDKNet.Test/ && dotnet add package AltCover && cd ../
  - dotnet restore
  
script:
  - cd AlipaySDKNet && dotnet build && cd ..
  - cd AlipaySDKNet.Test && dotnet build && cd ..
  - dotnet test /p:AltCover=true

after_success:
  - bash <(curl -s https://codecov.io/bash)